### ISSUE TITLE
第五个Issues

### ISSUE THREAD

**Issue by haozhihao** [Reginer/VeryFastjson#5]
虽然不知道是什么问题，但是你不可能没问题吧？

**Comment by GitHubHuan666** [comment]
这个问题，确实是个问题。大家看看怎么找出问题PS：废话文学

**Comment by haozhihao** [comment]
> 这个问题，确实是个问题。大家看看怎么找出问题PS：废话文学

我不是这方面的专家，但我还是想要发表一下我的观点，在我仔细看过你的问题经过长时间的思考后，我其实也不知道要怎么回答，正如我一开始说的，我不是这方面的专家

**Comment by lhjgege** [comment]
> > 这个问题，确实是个问题。大家看看怎么找出问题PS：废话文学
> 
> 我不是这方面的专家，但我还是想要发表一下我的观点，在我仔细看过你的问题经过长时间的思考后，我其实也不知道要怎么回答，正如我一开始说的，我不是这方面的专家

我认真的思考了一下想回答你的问题，但是再三考虑后不知道如何回答，正如你所说的一样我不是这方面的专家。

**Comment by Reginer** [comment]
无法保证不出现问题，但是发现问题会很快处理，哪怕很快时间内解决不了，也会很快关闭问题
